.\"                                      Hey, EMACS: -*- nroff -*-
.TH BIN2HEX 1 "June 22 2018"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
bin2hex \- display binary content as hexadecimal
.SH SYNOPSIS
.B bin2hex
.SH DESCRIPTION
.B bin2hex
reads from its standard input, and outputs the value of each byte it
reads as a hexadecimal pair.
.PP
.SH OPTIONS
This program has no options.
.SH SEE ALSO
.BR infnoise (8).
