.\"                                      Hey, EMACS: -*- nroff -*-
.TH DICE 1 "June 22 2018"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
dice \- roll dice
.SH SYNOPSIS
.B dice
.RI < file >
.RI < dice >
.RI < sides >
.SH DESCRIPTION
.B dice
simulates a dice roll, using data from
.I file
to roll
.I dice
dice with
.I sides
sides each.
.PP
A common value for
.I file
is
.BR /dev/random .
.PP
.SH OPTIONS
This program has no options.
.SH SEE ALSO
.BR infnoise (8).
