.\"                                      Hey, EMACS: -*- nroff -*-
.TH FLIPBITS 1 "June 24 2018"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
flipbits \- flip bits
.SH SYNOPSIS
.B flipbits
.RI [ width ]
.SH DESCRIPTION
.B infnoise-flipbits
flips the bits in its input data (from standard input),
.I width
bits at a time (8 by default), and outputs the result to standard
output.
.PP
.SH OPTIONS
This program has no options.
.SH SEE ALSO
.BR infnoise (8).
