.\"                                      Hey, EMACS: -*- nroff -*-
.TH PASSGEN 1 "June 25 2018"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
passgen \- generates passwords by rolling dice
.SH SYNOPSIS
.B passgen
.RI < file >
.RI < size >
.SH DESCRIPTION
.B passgen
generates an alphabetic password by rolling a 26-sided die, fed from
.IR file ,
.I size
times.
.SH OPTIONS
This program has no options.
.SH SEE ALSO
.BR infnoise (8).
